# Generated by Django 3.2 on 2021-06-23 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 18, 0, 4, 771141, tzinfo=utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
