# Generated by Django 3.2 on 2021-07-08 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210707_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 8, 34, 48, 780935, tzinfo=utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
