# Generated by Django 3.2 on 2021-07-08 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 56, 33, 693696, tzinfo=utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
