# Generated by Django 3.2 on 2021-07-08 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 32, 14, 887279), verbose_name='کاربر ویژه تا'),
        ),
    ]
