# Generated by Django 3.2 on 2021-07-08 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0023_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 33, 57, 684278), verbose_name='کاربر ویژه تا'),
        ),
    ]
