# Generated by Django 3.2 on 2021-07-10 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0024_alter_user_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 12, 17, 7, 857197), verbose_name='کاربر ویژه تا'),
        ),
    ]
