# Generated by Django 3.2 on 2021-07-10 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0025_auto_20210710_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 12, 22, 19, 157289), verbose_name='کاربر ویژه تا'),
        ),
    ]
