# Generated by Django 3.2 on 2021-04-26 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210426_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 11, 31, 20, 900411, tzinfo=utc)),
        ),
    ]
