# Generated by Django 3.2 on 2021-04-26 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210426_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 17, 14, 1, 220390, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
