# Generated by Django 3.2 on 2021-04-27 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 13, 12, 23, 240750, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
