# Generated by Django 3.2 on 2021-05-03 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20210503_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 3, 14, 204230, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
