# Generated by Django 3.2 on 2021-05-05 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20210503_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 16, 1, 45, 993552, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
