# Generated by Django 3.2 on 2021-05-05 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 16, 23, 55, 465359, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
