# Generated by Django 3.2 on 2021-06-15 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 17, 13, 53, 224243, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
