# Generated by Django 3.2 on 2021-06-23 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 18, 0, 4, 776129, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
