# Generated by Django 3.2 on 2021-07-08 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20210708_1304'),
        ('Blog', '0018_auto_20210707_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 8, 34, 48, 808890, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
