# Generated by Django 3.2 on 2021-07-08 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_auto_20210708_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 8, 38, 5, 642190, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
