# Generated by Django 3.2 on 2021-07-08 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_auto_20210708_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس آی پی', 'verbose_name_plural': 'آدرس های آی پی'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 12, 57, 57, 242691, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
