# Generated by Django 3.2 on 2021-07-08 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_auto_20210708_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 12, 57, 59, 870042, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
