# Generated by Django 3.2 on 2021-07-08 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_alter_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Blog.IPAddress', verbose_name='بازید ها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 12, 58, 16, 245117, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
