# Generated by Django 3.2 on 2021-07-08 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 10, 56, 300467, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
