# Generated by Django 3.2 on 2021-07-08 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0027_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 14, 5, 785787, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
