# Generated by Django 3.2 on 2021-07-08 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0028_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='Blog.ArticleHit', to='Blog.IPAddress', verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 14, 50, 657443, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
