# Generated by Django 3.2 on 2021-07-08 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0029_auto_20210708_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Blog.IPAddress', verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 31, 6, 550449, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
        migrations.DeleteModel(
            name='ArticleHit',
        ),
    ]
