# Generated by Django 3.2 on 2021-07-08 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0031_auto_20210708_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 49, 12, 847642, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='آدرس آی\u200cپی'),
        ),
        migrations.DeleteModel(
            name='ArticleHit',
        ),
    ]
