# Generated by Django 3.2 on 2021-07-08 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0032_auto_20210708_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.ipaddress', verbose_name='بازدید ها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 53, 29, 701573, tzinfo=utc), verbose_name='تاریخ انتشار'),
        ),
    ]
