# Generated by Django 3.2 on 2021-07-08 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0037_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 32, 17, 269823), verbose_name='تاریخ انتشار'),
        ),
    ]
