# Generated by Django 3.2 on 2021-07-08 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0038_alter_article_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 33, 57, 701233), verbose_name='تاریخ انتشار'),
        ),
    ]
