# Generated by Django 3.2 on 2021-07-10 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0039_auto_20210708_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Blog.IPAddress', verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 12, 17, 7, 873155), verbose_name='تاریخ انتشار'),
        ),
    ]
