# Generated by Django 3.2 on 2021-07-10 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0040_auto_20210710_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 12, 22, 19, 173212), verbose_name='تاریخ انتشار'),
        ),
    ]
